config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :pages do
  collection do
    get :login
	get :about
  get :account
  get :results
  get :dwelling
  end
end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def login
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>David</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <a href="<%= root_path %>" style="text-decoration:none">
  <%= image_tag("logo.png", width: '900px') %>
  </a>
  <a href="<%= login_pages_path %>" style="text-decoration:none">
  <%= image_tag("my_account.png", width: '163px') %>
  </a>
  <a href="<%= about_pages_path %>" style="text-decoration:none">
  <%= image_tag("about_us.png", width: '163px') %>
  </a>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About DPM</h1>
<body>
We pride ourselves in being the best property managment in Brisbane. Our motto
is "If there is a property, we can manage it".<br><br>

Hi, I'm David, and when I was 12 years old I dreamt of opening my own property
management company. When I was 15, I made this true, being the youngest graduate
of any business school in the country. Here at DPM, we like to make history.
We hope you join us for the ride.

<br><br>
<h2>Contact us</h2>
David's Email: david@david.com<br>
David's Phone: 04daviddavid

app/views/pages/account.html.erb
<h1>My Account</h1>
<body>

This is where the dynamically created links will be generated in order to
make each account different.

<br><br>

Staff:<br>
- Properties I manage<br>
- Inspections upcoming<br>
- Update Personal Information<br>
<br><br>
David:<br>
- Staff details<br>
- Tenant details<br>
- Property Owner details<br>
<br><br>
Tenant:<br>
- My Contract<br>
- Update Personal Information<br>
<br><br>
Property Owner:<br>
- Properties Currently on DPM<br>
- Update Property Information<br>
- Update Personal Information<br>

app/views/pages/dwelling.html.erb
<h1>Dwelling</h1>
<body>

This is the page where the specific information about a selected property
will be dynamically placed

<br><br>
- Price per week<br>
- Bedrooms<br>
- Bathrooms<br>
- Car Spaces<br>
- Address<br>
- Furnished<br>
- Photo (maybe)<br>
- Book times for an inspection (Domain.com.au does this well)<br>

app/views/pages/login.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>David's Property Management | Registration</title>
</head>

<body>

<h1>Sign In</h1>
All fields with * are required<br><br>

<form>
Username*<br>
<input type="text" name="username" placeholder="Username" required><br><br>
Password*<br>
<input type="password" name="password" placeholder="Password" required><br><br>

<a href="<%= account_pages_path %>">
<input type="submit" value="Sign In">
</a>
</form>

<h1>Don't have an account? Register</h1>
	All fields with * are required<br><br>
	<form>
	Name*<br>
	<input type="text" name="fname" placeholder="First Name" required>
	<input type="text" name="lname" placeholder="Last Name" required><br>
	Email*<br>
	<input type="email" name="email" required><br>
	Contact Number<br>
	<input type="number" name="phNo"><br>
	Password*<br>
	<input type="password" name="password1" required><br>
	Confirm password*<br>
	<input type="password" name="password2" required><br><br>
	<input type="submit" value="Submit">
	</form>
</body>
</html>

app/views/pages/results.html.erb
<h1>Search Results</h1>
<body>

Properties will be dynamically placed here based on the filters in place

<br><br>
<a href="<%= dwelling_pages_path %>">
  DWELLING.html
</a>

app/views/welcome/index.html.erb
<h1> Welcome to Davids Property Management </h1>
<br><br>

<h2> Search for Properties </h2>



<div id="onimage">

<br><br><br><br><br><br><br><br>

<div id="centerdiv">
<form>
<p align="center">Search by Suburb</p>
<input type="search" name="searchbar" placeholder="Suburb">
</form>
</div>

<br>


<table align="center" width="380">
<tr>
<td>
<form>
Rent Per Week<br>
<select name="Rent">
	<option value="Any" hidden>Rent Value</option>
	<option value="sml">$0-$150</option>
	<option value="mid">$150-$300</option>
	<option value="lrg">$400</option>
	<option value="Any">Any</option>
</form>
</td>

<td>
<form>
Type of Dwelling<br>
<select name="Dwelling">
	<option value="Any" hidden>Dwelling Type</option>
	<option value="sml">House</option>
	<option value="mid">Appartment</option>
	<option value="Any">Any</option>
</form>
</td>

<td>
<form>
Furnished<br>
<select name="Furnished">
	<option value="Any" hidden>Furnished</option>
	<option value="yes">Yes</option>
	<option value="no">No</option>
	<option value="Any">Any</option>
</form>
</td>

</tr>

</table>

<br><br>

<div id="centerdiv">
<a href="<%= results_pages_path %>">
<input type="submit" value="Search">
</a>
</div>
<br><br><br><br><br><br><br>